### PR TITLE
Add feature to change the notification window’s placement

### PR DESCRIPTION
**Pull request by mntone**
This patch is able to change notification window’s placement. Users can choose position & display.

### Sample screenshot

Settings pane

### CODE REVIEW

**Comment by mntone** [comment]
## Add support for multiple wallpaper for multiple display

Add feature to choose difference wallpapers for each display. Change choosing wallpaper algorithm. But, it is compatible.

Please see the following naming list for selection algorithm:

- All displays, all desktop: `0.ext` or `0-0.ext`
- First display, all desktop: `1.ext` or `1-n.ext` (n = natural number)
- Second display, second desktop: `2-2.ext`

**Comment by mntone** [comment]
## Add support about placement preview

Merge its commit if you need this function.

image

**Comment by Grabacr07** [comment]
Awesome 👍

Could you please resolve conflicts?
Then I will merge.

**Comment by Grabacr07** [comment]
Thanks, merged.

**Pull request merged**
